name: Check Security

on:
  pull_request:
    types: [opened, synchronize] 

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.json

  audit: 
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
      - name: Install dependencies for production
        run: yarn npm audit